version: '3.8'

services:
  # OCR + AI Agent service
  ocr-ai-agent:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: genesilico-ocr-ai-agent
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
      - ../.env:/app/.env
    # Environment variables from .env file, with secure defaults
    env_file:
      - ../.env
    environment:
      - MONGODB_URL=mongodb+srv://genesilico:genesilico123@cluster0.x4roimb.mongodb.net
      - MONGODB_DB=genesilico-database
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - ENV=production
    networks:
      - genesilico-network

networks:
  genesilico-network:
    driver: bridge
