version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: genesilico-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - genesilico-network

  # OCR + AI Agent service
  ocr-ai-agent:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: genesilico-ocr-ai-agent
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
      - ../.env:/app/.env
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB=genesilico_ocr
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - ENV=production
    networks:
      - genesilico-network

volumes:
  mongodb_data:

networks:
  genesilico-network:
    driver: bridge
